name: "build-jdk-openj9 with adoptopenjdk openjdk-build linux"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: buildJDK
      with: 
        javaToBuild: 'jdk13u'
    - uses: actions/upload-artifact@v2-preview
      with:
        name: buildJDK
        path: ./**/artifacts/*.tar.gz/