name: "build-jdk-openj9 with adoptopenjdk openjdk-build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: buildOpenj9
      with: 
        javaToBuild: 'jdk11u'
    - run: ${{ steps.buildOpenj9.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2-preview
      with:
        name: JDK
        path: ./**/artifacts/*.tar.gz/