name: "build-jdk-hotspot"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: buildHotspot
      with: 
        javaToBuild: 'jdk11u'